# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: codecov
on:
  pull_request:
  push:
    branches:
    - main
permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
      with:
        egress-policy: audit

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        go-version: '1.20'
    - run: "PATH=/usr/local/go/bin:$PATH make test-cover"
    - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
      with:
        file: ./coverage.out
        fail_ci_if_error: true
